netfilter: Add missing array nfnl_group2type
/home/adithya/a6000kernel/net/netfilter/nfnetlink.c: In function 'nfnetlink_bind':
/home/adithya/a6000kernel/net/netfilter/nfnetlink.c:220:13: error: 'nfnl_group2type' undecla
red (first use in this function)
  int type = nfnl_group2type[group];